### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Fenwick17** [erikdubois/antergosi3#1]
Is it possible to revert the steps taken here? I have tried to manually remove i3 but when I do all of the script steps remain, opening firefox etc.  
I am wanting to try a completely fresh setup, but cant seem to remove the scripts.

**Comment by erikdubois** [comment]
opening firefox could be an keyboard shortcut??
if you delete i3 folder .... you will have no i3 anymore 
sure that you do not have another i3  older somewhere that is actually doing the work?
happened to me once - now I only use ~/.config/i3 but i used to use ~/.i3
