### ISSUE TITLE
no necessary files/commands executed in 600-install-personal-settings-vx.sh

### ISSUE THREAD

**Issue by triple1c86** [erikdubois/antergosi3#2]
"600-install-personal-settings-vx.sh                     (necessary to be able to boot into i3 automatically)
It will put all necessary files/commands in the right places (startx, xintrc,...)"

erm it just created folders but didnt edit any files right?
i cant startx into i3wm.. or maybe i'm just too noob.. Please help thanks.

**Comment by erikdubois** [comment]
it creates folders
other scripts will write stuff to these folders
[https://github.com/erikdubois/AntergosI3/blob/master/installation/settings/.xinitrc](https://github.com/erikdubois/AntergosI3/blob/master/installation/settings/.xinitrc)
will make sure you can boot into i3. It goes in the root of your home directory.
copy/paste all .files in that settings folder to the the root of you home directory

**Comment by neverfox** [comment]
What other scripts? It's the last one before autologin (680) and firebox (700). After following all the steps, it boots to a prompt, not i3.

**Comment by erikdubois** [comment]
nr 1000 is your i3 config - do not do that one 
and no i3 just a prompt
